apiVersion: v1
kind: ConfigMap
metadata:
  name: central-config
data:
  log_level: "info"
  CENTRAL_LOG_REQUESTS: "true"
  streamer_dead_timeout: "60s"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
stringData:
  pgpass: "668bfadfd824"
  config-ext: "0877d9c6-f1f3-4070-a970-3e0e54c41c00"
  cluster-key: "clusterkey"
---
apiVersion: v1
kind: Secret
metadata:
  name: license
stringData:
  license_key: put-your-own-license-here
  edit_auth: "root:password"