apiVersion: v1
kind: ConfigMap
metadata:
  name: central-config
  namespace: catena-se
data:
  log_level: "info"
  CENTRAL_LOG_REQUESTS: "true"
  streamer_dead_timeout: "60s"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  namespace: catena-se
stringData:
  pgpass: 668bfadfd824
---
apiVersion: v1
kind: Secret
metadata:
  name: license
  namespace: catena-se
stringData:
  license_key: put-your-own-license-here
  edit_auth: "root:password"